language: java
jdk:
  - oraclejdk8
env:
  - release=default
#  - release=10.0
script:
  - ant boot -Daccept.license=true -Dbootstrap=$release
  - sagccant masters test -Denv=$release
  - sagccant installers mirrors -Denv=$release
