language: java
jdk:
  - oraclejdk8
env:
  - release=default
#  - release=10.0
script:
  - ant boot -Daccept.license=true -Dbootstrap=$release
  - ~/sag/cc/CommandCentral/client/bin/sagccant masters test installers mirrors -Denv=$release
